version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo 'Build execution started...'
      - apt-get update -y && apt-get install sshpass -y
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - LATEST_BE_IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
  build:
    commands:
      - mvn clean install
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/java-web-app:sh deploy.sh$LATEST_BE_IMAGE_TAG .
      - docker image push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/java-web-app:$LATEST_BE_IMAGE_TAG
      - sshpass -p "$SRVR_PWD" ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP "sh deploy.sh"
  post_build:
    commands:
      - echo 'Build execution completed...'
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
